# Generated by Django 3.2.16 on 2023-02-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230203_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
